# Generated by Django 3.2.3 on 2021-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stripped_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stripped_name', models.CharField(max_length=200)),
                ('csfd_link', models.CharField(max_length=200)),
                ('movies', models.ManyToManyField(to='crawler.Movie')),
            ],
        ),
    ]
